TMP := $(USERPROFILE)\AppData\Local\Temp
TEMP := $(USERPROFILE)\AppData\Local\Temp
.PHONY=  dev run 
dev:
	GOCACHE=/c/Users/tonym/AppData/Local/go-cache GOTMPDIR=/c/Users/tonym/AppData/Local/Temp/go-build GOPATH=/c/Users/tonym/go go tool air
run:
	go run ./cmd/server/main.go
